
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET.SchoolGrade
{

    [Config]
    public partial class SchoolGradeConfigCategory : Singleton<SchoolGradeConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<int, SchoolGrade.SchoolGradeConfig> _dataMap;
        private readonly List<SchoolGrade.SchoolGradeConfig> _dataList;
        
        public SchoolGradeConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, SchoolGrade.SchoolGradeConfig>();
            _dataList = new List<SchoolGrade.SchoolGradeConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                SchoolGrade.SchoolGradeConfig _v;
                _v = global::ET.SchoolGrade.SchoolGradeConfig.DeserializeSchoolGradeConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<int, SchoolGrade.SchoolGradeConfig> GetAll() => _dataMap;
        public Dictionary<int, SchoolGrade.SchoolGradeConfig> DataMap => _dataMap;
        public List<SchoolGrade.SchoolGradeConfig> DataList => _dataList;

        public SchoolGrade.SchoolGradeConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public SchoolGrade.SchoolGradeConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

