
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET.SchoolGrade
{
    [EnableClass]
    public sealed partial class SchoolGradeConfig : Luban.BeanBase
    {
        public SchoolGradeConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            GradeName = _buf.ReadString();
            {int n0 = _buf.ReadSize(); ClassIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); ClassIds.Add(_e0);}}

            EndInit();
        }

        public static SchoolGradeConfig DeserializeSchoolGradeConfig(ByteBuf _buf)
        {
            return new SchoolGrade.SchoolGradeConfig(_buf);
        }

        /// <summary>
        /// 这是id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string GradeName;
        /// <summary>
        /// 班级id
        /// </summary>
        public readonly System.Collections.Generic.List<int> ClassIds;
        public System.Collections.Generic.List<SchoolGrade.GradeClassConfig> ClassIds_Ref;
    
        public const int __ID__ = 443896122;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            ClassIds_Ref = new System.Collections.Generic.List<SchoolGrade.GradeClassConfig>();
            foreach (var _v in ClassIds) { ClassIds_Ref.Add(GradeClassConfigCategory.Instance.GetOrDefault(_v)); }

            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "gradeName:" + GradeName + ","
            + "classIds:" + Luban.StringUtil.CollectionToString(ClassIds) + ","
            + "}";
        }

        partial void EndRef();
    }

}

