
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class GradeClassConfig : Luban.BeanBase
    {
        public GradeClassConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Grade = _buf.ReadString();

            EndInit();
        }

        public static GradeClassConfig DeserializeGradeClassConfig(ByteBuf _buf)
        {
            return new GradeClassConfig(_buf);
        }

        /// <summary>
        /// 这是id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Grade;
    
        public const int __ID__ = 2004143779;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "grade:" + Grade + ","
            + "}";
        }

        partial void EndRef();
    }

}

