
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [Config]
    public partial class GradeClassConfigCategory : Singleton<GradeClassConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<int, GradeClassConfig> _dataMap;
        private readonly List<GradeClassConfig> _dataList;
        
        public GradeClassConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, GradeClassConfig>();
            _dataList = new List<GradeClassConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                GradeClassConfig _v;
                _v = global::ET.GradeClassConfig.DeserializeGradeClassConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<int, GradeClassConfig> GetAll() => _dataMap;
        public Dictionary<int, GradeClassConfig> DataMap => _dataMap;
        public List<GradeClassConfig> DataList => _dataList;

        public GradeClassConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public GradeClassConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

