
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class SchoolGradeConfig : Luban.BeanBase
    {
        public SchoolGradeConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            GradeName = _buf.ReadString();
            {int n0 = _buf.ReadSize(); ClassId = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); ClassId.Add(_e0);}}

            EndInit();
        }

        public static SchoolGradeConfig DeserializeSchoolGradeConfig(ByteBuf _buf)
        {
            return new SchoolGradeConfig(_buf);
        }

        /// <summary>
        /// 这是id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string GradeName;
        /// <summary>
        /// 班级id
        /// </summary>
        public readonly System.Collections.Generic.List<int> ClassId;
    
        public const int __ID__ = -1442165307;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "gradeName:" + GradeName + ","
            + "classId:" + Luban.StringUtil.CollectionToString(ClassId) + ","
            + "}";
        }

        partial void EndRef();
    }

}

