
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [Config]
    public partial class SchoolGradeConfigCategory : Singleton<SchoolGradeConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<int, SchoolGradeConfig> _dataMap;
        private readonly List<SchoolGradeConfig> _dataList;
        
        public SchoolGradeConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, SchoolGradeConfig>();
            _dataList = new List<SchoolGradeConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                SchoolGradeConfig _v;
                _v = global::ET.SchoolGradeConfig.DeserializeSchoolGradeConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<int, SchoolGradeConfig> GetAll() => _dataMap;
        public Dictionary<int, SchoolGradeConfig> DataMap => _dataMap;
        public List<SchoolGradeConfig> DataList => _dataList;

        public SchoolGradeConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public SchoolGradeConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

